// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-bio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_bio_default = defineTool({
  name: "get_bio",
  title: "Get bio",
  description: "Return a concise bio and contact links for Dr. Justinas Mi\u0161eikis.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Dr. Justinas Mi\u0161eikis - AI Strategy Advisor, speaker, and researcher (PhD in Robotics & AI).",
          "Currently at Sony AI. Based in Zurich, Switzerland.",
          "Services: Advisory, Speaking, Technical Due Diligence.",
          "Website: https://jmiseikis.lovable.app",
          "LinkedIn: https://www.linkedin.com/in/miseikis/",
          "Contact via the website contact form."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the professional services Justinas Mi\u0161eikis offers (Advisory, Speaking, Technical Due Diligence) with page URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          [
            {
              name: "AI Strategy Advisory",
              url: "https://jmiseikis.lovable.app/advisory",
              summary: "Fractional AI advisory for founders and executives: strategy, roadmap, agent architecture."
            },
            {
              name: "Keynote Speaking",
              url: "https://jmiseikis.lovable.app/speaking",
              summary: "Keynotes and workshops on applied AI, robotics, and AI agents."
            },
            {
              name: "Technical Due Diligence",
              url: "https://jmiseikis.lovable.app/due-diligence",
              summary: "Independent AI/ML technical due diligence for VCs and acquirers."
            },
            {
              name: "AI Agents Strategy Guide",
              url: "https://jmiseikis.lovable.app/ai-agents-strategy",
              summary: "Guide for enterprises adopting AI agents."
            }
          ],
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/tools/list-tech-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SHEET_ID = "1k4vfFfSX9Pmi5tNVuijUmubuTPSoFvBnIxC1kH_25x4";
var SHEET_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json`;
function parseGviz(text) {
  const match = text.match(/google\.visualization\.Query\.setResponse\(([\s\S]+)\);?/);
  if (!match) return [];
  try {
    const json = JSON.parse(match[1]);
    return json?.table?.rows ?? [];
  } catch {
    return [];
  }
}
var list_tech_events_default = defineTool3({
  name: "list_tech_events",
  title: "List tech events",
  description: "List curated European tech, AI, and robotics events from the Tech Events directory. Optionally filter by a search query and limit results.",
  inputSchema: {
    query: z.string().optional().describe("Case-insensitive substring match against event name, location, or topic."),
    limit: z.number().int().positive().max(100).optional().describe("Max events to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const res = await fetch(SHEET_URL);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch events: ${res.status}` }], isError: true };
    }
    const rows = parseGviz(await res.text());
    const events = rows.map((r) => r.c.map((cell) => cell?.f ?? cell?.v ?? "")).filter((cols) => cols.some((c) => c && String(c).trim().length > 0));
    const q = query?.toLowerCase().trim();
    const filtered = q ? events.filter((cols) => cols.some((c) => String(c).toLowerCase().includes(q))) : events;
    const capped = filtered.slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(capped, null, 2) }],
      structuredContent: { count: capped.length, total: filtered.length, rows: capped }
    };
  }
});

// src/lib/mcp/tools/list-swiss-vcs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var SHEET_ID2 = "1FqX_G9qw9srGHumCWfQH1L4RCDlW4EtJ8-iXTfzsblI";
var SHEET_URL2 = `https://docs.google.com/spreadsheets/d/${SHEET_ID2}/gviz/tq?tqx=out:json`;
function parseGviz2(text) {
  const match = text.match(/google\.visualization\.Query\.setResponse\(([\s\S]+)\);?/);
  if (!match) return [];
  try {
    const json = JSON.parse(match[1]);
    return json?.table?.rows ?? [];
  } catch {
    return [];
  }
}
var list_swiss_vcs_default = defineTool4({
  name: "list_swiss_vcs",
  title: "List Swiss VCs",
  description: "List Swiss venture capital firms from the Swiss VCs directory. Optionally filter by a search query (sector, stage, name) and limit results.",
  inputSchema: {
    query: z2.string().optional().describe("Case-insensitive substring match across all columns."),
    limit: z2.number().int().positive().max(100).optional().describe("Max VCs to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const res = await fetch(SHEET_URL2);
    if (!res.ok) {
      return { content: [{ type: "text", text: `Failed to fetch VCs: ${res.status}` }], isError: true };
    }
    const rows = parseGviz2(await res.text());
    const vcs = rows.map((r) => r.c.map((cell) => cell?.f ?? cell?.v ?? "")).filter((cols) => cols.some((c) => c && String(c).trim().length > 0));
    const q = query?.toLowerCase().trim();
    const filtered = q ? vcs.filter((cols) => cols.some((c) => String(c).toLowerCase().includes(q))) : vcs;
    const capped = filtered.slice(0, limit ?? 25);
    return {
      content: [{ type: "text", text: JSON.stringify(capped, null, 2) }],
      structuredContent: { count: capped.length, total: filtered.length, rows: capped }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jmiseikis-mcp",
  title: "Justinas Mi\u0161eikis Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for the Dr. Justinas Mi\u0161eikis portfolio site. Use `get_bio` for a short bio and links, `list_services` for advisory/speaking/due-diligence offerings, `list_tech_events` for the curated European tech/AI/robotics events directory, and `list_swiss_vcs` for the Swiss VC directory. All tools are read-only and safe to call.",
  tools: [get_bio_default, list_services_default, list_tech_events_default, list_swiss_vcs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
